/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a User resource.
         * @description Retrieves a User resource.
         */
        get: operations["api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of User resources.
         * @description Retrieves the collection of User resources.
         */
        get: operations["api_users_get_collection"];
        put?: never;
        /**
         * Creates a User resource.
         * @description Creates a User resource.
         */
        post: operations["api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of User resources.
         * @description Retrieves the collection of User resources.
         */
        get: operations["api_usersroles_get_collection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a User resource.
         * @description Retrieves a User resource.
         */
        get: operations["api_users_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the User resource.
         * @description Removes the User resource.
         */
        delete: operations["api_users_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the User resource.
         * @description Updates the User resource.
         */
        patch: operations["api_users_id_patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a user token.
         * @description Creates a user token.
         */
        post: operations["login_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "User.CreateUserInput.jsonld": {
            email?: string;
            password?: string;
        };
        "User.PatchUserInput": {
            email?: string;
            password?: string;
            roles?: string[];
        };
        "User.jsonld": {
            readonly "@context"?: string | ({
                "@vocab": string;
                /** @enum {string} */
                hydra: "http://www.w3.org/ns/hydra/core#";
            } & {
                [key: string]: unknown;
            });
            readonly "@id"?: string;
            readonly "@type"?: string;
            id?: number | null;
            /** Format: uuid */
            uuid?: string;
            email?: string | null;
            /** @description The user roles */
            roles?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page identifier */
                page?: string;
                /** @description Filter email by partial string match */
                "email[contains]"?: string;
                /** @description Filter email by partial string match at the end */
                "email[endswith]"?: string;
                /** @description Filter email by partial string match at the beginning */
                "email[startswith]"?: string;
                /** @description Filter email by equal to a value */
                "email[eq]"?: string;
                /** @description Filter email by not equal to a value */
                "email[neq]"?: string;
                /** @description Filter email by in a list of values */
                "email[in]"?: string;
                /** @description Filter email by not in a list of values */
                "email[nin]"?: string;
                /** @description Filter email by is null value */
                "email[isnull]"?: string;
                /** @description Filter email by is not null value */
                "email[isnotnull]"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": {
                        "hydra:member": components["schemas"]["User.jsonld"][];
                        "hydra:totalItems"?: number;
                        /** @example {
                         *       "@id": "string",
                         *       "type": "string",
                         *       "hydra:first": "string",
                         *       "hydra:last": "string",
                         *       "hydra:previous": "string",
                         *       "hydra:next": "string"
                         *     } */
                        "hydra:view"?: {
                            /** Format: iri-reference */
                            "@id"?: string;
                            "@type"?: string;
                            /** Format: iri-reference */
                            "hydra:first"?: string;
                            /** Format: iri-reference */
                            "hydra:last"?: string;
                            /** Format: iri-reference */
                            "hydra:previous"?: string;
                            /** Format: iri-reference */
                            "hydra:next"?: string;
                        };
                        "hydra:search"?: {
                            "@type"?: string;
                            "hydra:template"?: string;
                            "hydra:variableRepresentation"?: string;
                            "hydra:mapping"?: {
                                "@type"?: string;
                                variable?: string;
                                property?: string | null;
                                required?: boolean;
                            }[];
                        };
                    };
                };
            };
        };
    };
    api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new User resource */
        requestBody: {
            content: {
                "application/ld+json": components["schemas"]["User.CreateUserInput.jsonld"];
            };
        };
        responses: {
            /** @description User resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_usersroles_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page identifier */
                page?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": {
                        "hydra:member": components["schemas"]["User.jsonld"][];
                        "hydra:totalItems"?: number;
                        /** @example {
                         *       "@id": "string",
                         *       "type": "string",
                         *       "hydra:first": "string",
                         *       "hydra:last": "string",
                         *       "hydra:previous": "string",
                         *       "hydra:next": "string"
                         *     } */
                        "hydra:view"?: {
                            /** Format: iri-reference */
                            "@id"?: string;
                            "@type"?: string;
                            /** Format: iri-reference */
                            "hydra:first"?: string;
                            /** Format: iri-reference */
                            "hydra:last"?: string;
                            /** Format: iri-reference */
                            "hydra:previous"?: string;
                            /** Format: iri-reference */
                            "hydra:next"?: string;
                        };
                        "hydra:search"?: {
                            "@type"?: string;
                            "hydra:template"?: string;
                            "hydra:variableRepresentation"?: string;
                            "hydra:mapping"?: {
                                "@type"?: string;
                                variable?: string;
                                property?: string | null;
                                required?: boolean;
                            }[];
                        };
                    };
                };
            };
        };
    };
    api_users_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated User resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["User.PatchUserInput"];
            };
        };
        responses: {
            /** @description User resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/ld+json": components["schemas"]["User.jsonld"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The login data */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        readonly token: string;
                    };
                };
            };
        };
    };
}
