enum Roles {
  ROLE_USER = 'ROLE_USER',
  ROLE_ADMIN = 'ROLE_ADMIN',
  USER_GET_ONE = 'USER_GET_ONE',
  USER_GET_COLLECTION = 'USER_GET_COLLECTION',
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

}

export default Roles;